.TH kindleclip 1 "09 Aug 2011"
.SH NAME
kindleclip \- User interface for managing Amazon Kindle's My Clippings.txt file
.SH SYNOPSIS
.B kindleclip
.RI [ clippings_file ] 
.SH DESCRIPTION
Amazon Kindle devices store a \fIMy Clippings.txt\fP file, where the
bookmarks, highlights and notes are kept. This application allows you
to search within the clippings, filter the contents, and copy and
paste to other applications.
.
This program is in no way endorsed, promoted or should be associated
with Amazon. It is not –and does not aim to be– an official Kindle
project.
.SH OPTIONS
\fIkindleclip\fP accepts as its only argument the path to the \fIMy
Clippings.txt\fP file to use; if none is provided, it will try to open
it in the current directory, and exit with an error message if it does
not exist.
.SH AUTHOR
This program was written by Gunnar Wolf <gwolf@gwolf.org>.
